### ISSUE TITLE
Error at compilation

### ISSUE THREAD

**Issue by dudaerich** [bayertom/libalgo#1]
During the compilation it writes following error. It is compiled in linux. You can try it to compile from github repository https://github.com/moravianlibrary/libalgo. Instructions are in the INSTALL file.

![image](https://cloud.githubusercontent.com/assets/2317374/6333107/ac076a38-bb8a-11e4-9ec5-6479d51b5a83.png)

**Comment by bayertom** [comment]
All g++ errors have been fixed...

Dne 23. 2. 2015 v 18:36 Erich Duda napsal(a):

> Dobrý deň,
> pri kompilácii mi vypisuje nasledovnú chybu. Kompilujem to na linuxe, 
> môžete to skúsiť skompilovať z tadeto 
> https://github.com/moravianlibrary/libalgo inštrukcie sú v súbore INSTALL.
> 
> image 
> https://cloud.githubusercontent.com/assets/2317374/6333107/ac076a38-bb8a-11e4-9ec5-6479d51b5a83.png
> 
> Mohli by ste sa na to pozrieť? Ďakujem.
> 
> Erich
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/bayertom/libalgo/issues/1.

---

Tato zpráva byla zkontrolována na viry programem Avast Antivirus.
http://www.avast.com

## 

---

Pokud je tento e-mail součástí obchodního jednání, Přírodovědecká fakulta 
Univerzity Karlovy v Praze:
a) si vyhrazuje právo jednání kdykoliv ukončit a to i bez uvedení důvodu,
b) stanovuje, že smlouva musí mít písemnou formu,
c) vylučuje přijetí nabídky s dodatkem či odchylkou,
d) stanovuje, že smlouva je uzavřena teprve výslovným dosažením shody na 
všech náležitostech smlouvy.

**Comment by dudaerich** [comment]
I tried it but I got following error.

![image](https://cloud.githubusercontent.com/assets/2317374/6522577/a6bea546-c3e6-11e4-9282-d0e503ff1fa1.png)

**Comment by dudaerich** [comment]
Bug fixed in https://github.com/bayertom/libalgo/pull/4
Please check if the compilation works also under the Windows.
