### ISSUE TITLE
Errors occured during the compilation of detectproj.cpp

### ISSUE THREAD

**Issue by dudaerich** [bayertom/libalgo#5]
When I tried to use compiled library with https://github.com/moravianlibrary/detectproj, during the compilation it occurred errors. The errors are in *.hpp files. You probably forgot to update *.hpp files, when you changed the *.h files.

![image](https://cloud.githubusercontent.com/assets/2317374/6524321/8f1493e4-c3f8-11e4-9b14-6b0889dc68af.png)

**Comment by bayertom** [comment]
All compile errors have been fixed: 2 forward declarations added, the amount of formal parameters changed in accordance with the refined method.
